### ISSUE TITLE
Can the "Applies to" be updated to include Windows Server 2019

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#4051]
This page also applies to Server 2019.

Also, should Windows 8 removed?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc50ab2-5b70-2b78-5345-cb261071fcc0
* Version Independent ID: c081e16d-cf9d-f9a7-e86c-80a38e33d211
* Content: [Hyper-V Virtual Machine Connection](https://docs.microsoft.com/en-gb/windows-server/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect?redirectedfrom=MSDN#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by illfated** [comment]
As long as the page documentation still applies to Windows 8.1 and Windows 8, I don't think it should be removed before Windows 8.1 and Windows 8 are no longer supported. There might still be valid Enterprise use of those Windows versions out there.

**Comment by illfated** [comment]
@doctordns : Unless there is anything else you would like to change to complete a resolution of this issue, I think we can safely say that this ticket is resolved.

**Comment by illfated** [comment]
#sign-off

**Comment by doctordns** [comment]
So far as I can see, this is not resolved, in that Server 2019 has not been added?

**Comment by illfated** [comment]
Fair enough. Opening a new PR to resolve that issue.

**Comment by doctordns** [comment]
Should Server 2022 be added?

**Comment by illfated** [comment]
> Should Server 2022 be added?

Way too early, I don't think it will be added before the version is publicly released to everyone.

**Comment by doctordns** [comment]
The reason I ask is that Insiders Builds now have the Server 2022 branding as 20H1.

**Comment by illfated** [comment]
I would not count on information being added before the release (RTM) version has been published, unless you are referring to Insiders Preview content pages.
