### ISSUE TITLE
Specifying the cases where specific error messages/Windows event occur

### ISSUE THREAD

**Issue by DaPadrePedro** [MicrosoftDocs/windowsserverdocs#5734]
Hi,

Is it possible to specify which error message/Windows event occurs in which scenarios? For example, events 32002 and 32000 both describe the same, but when is 32000 displayed and when 32002? Or do they always both appear together? Idem dito for the other 6 error messages mentioned (I suppose these are logged in Windows events as well?).

Greetz,

Padre Pedro (Christophe Heereman)
From WinDoh, Belgium

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efee75e-7541-0166-76ac-81ecbe4cb022
* Version Independent ID: 35b346a7-ea72-325e-81c9-a1056dca72f4
* Content: [SMBv1 is not installed by default in Windows 10 version 1709, Windows Server version 1709 and later versions](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/smbv1-not-installed-by-default-in-windows)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/smbv1-not-installed-by-default-in-windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/smbv1-not-installed-by-default-in-windows.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Deland-Han** [comment]
@IngridAtMicrosoft We have modified the article with [PR2384](https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/2384). The issue is addressed.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by DaPadrePedro** [comment]
Hi, any idea why an edit of the modified page still shows the previous content?

**Comment by IngridAtMicrosoft** [comment]
@DaPadrePedro Not sure.  Please open a new GH issue.

**Comment by DaPadrePedro** [comment]
> @DaPadrePedro Not sure. Please open a new GH issue.

Et voila: issue #6046 :-)
